In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("place.csv")
df.head()

marks  experience  placed
0     20           4       0
1     78          20       1
2     38          13       1
3     15          10       0
4     32          11       0

In [3]:
df.shape

(230, 3)

In [4]:
df.isna().sum()

marks         0
experience    0
placed        0
dtype: int64

In [5]:
df.isnull().sum()

marks         0
experience    0
placed        0
dtype: int64

In [6]:
df['placed'].value_counts()

placed
1    131
0     99
Name: count, dtype: int64

In [9]:
# split x and y

x=df.drop(columns=['placed'])
y=df['placed']

In [10]:
x

marks  experience
0       20           4
1       78          20
2       38          13
3       15          10
4       32          11
..     ...         ...
225     25           2
226     10          28
227     34          13
228     87          27
229     64           2

[230 rows x 2 columns]

In [11]:
y

0      0
1      1
2      1
3      0
4      0
      ..
225    0
226    0
227    1
228    1
229    1
Name: placed, Length: 230, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [17]:
from sklearn.linear_model import LogisticRegression

In [20]:
lg=LogisticRegression()

In [21]:
model=lg.fit(x_train,y_train)

In [22]:
y=model.predict(x_test)
y

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1], dtype=int64)

In [25]:
y_test

127    1
4      0
167    1
37     0
121    0
85     1
34     0
41     1
74     1
207    1
165    0
98     0
204    0
119    1
215    1
175    0
109    1
65     0
118    0
149    1
78     1
48     0
226    0
117    0
114    1
229    1
196    1
203    1
148    0
145    0
32     0
208    1
91     1
31     1
112    0
35     1
39     1
174    0
133    1
93     1
158    1
185    0
33     1
108    0
188    1
22     1
Name: placed, dtype: int64

In [26]:
from mlxtend.plotting import plot_decision_region

ModuleNotFoundError: No module named 'mlxtend'

In [30]:
y_prob=model.predict_proba(x_test)[:,1]
y_prob

array([1.00000000e+00, 5.28753785e-02, 1.00000000e+00, 2.63199837e-06,
       1.82193754e-07, 9.99999998e-01, 2.22354550e-06, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 7.79862571e-10, 9.39167148e-02,
       1.05189220e-11, 9.99999985e-01, 9.10873151e-01, 2.76165662e-08,
       9.99008608e-01, 1.39611496e-03, 1.38437070e-09, 7.46151367e-02,
       1.83888948e-01, 1.89601357e-01, 5.16900309e-03, 1.17971069e-03,
       9.99999914e-01, 9.99981382e-01, 1.00000000e+00, 1.00000000e+00,
       2.49495654e-02, 6.65916662e-11, 1.95863667e-02, 1.00000000e+00,
       1.00000000e+00, 9.99711150e-01, 1.28376242e-10, 9.99943704e-01,
       9.99999899e-01, 5.59080324e-03, 5.47402204e-01, 1.00000000e+00,
       9.99999985e-01, 1.38437070e-09, 9.99999964e-01, 4.24014796e-04,
       1.00000000e+00, 9.99999999e-01])

In [31]:
(y_prob>=0.5).astype(int)

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1])

In [36]:
y_test

127    1
4      0
167    1
37     0
121    0
85     1
34     0
41     1
74     1
207    1
165    0
98     0
204    0
119    1
215    1
175    0
109    1
65     0
118    0
149    1
78     1
48     0
226    0
117    0
114    1
229    1
196    1
203    1
148    0
145    0
32     0
208    1
91     1
31     1
112    0
35     1
39     1
174    0
133    1
93     1
158    1
185    0
33     1
108    0
188    1
22     1
Name: placed, dtype: int64

In [3]:
import pandas as pd
data = pd.DataFrame({ 'Age': [30, 45, 50, 35, 40, 60], 

             'Body Temperature': [98.1, 99.5, 99.6, 98.0, 98.2, 100.2], 

              'Disease': ['No', 'Yes', 'Yes', 'No', 'No', 'Yes'] })
data

Age  Body Temperature Disease
0   30              98.1      No
1   45              99.5     Yes
2   50              99.6     Yes
3   35              98.0      No
4   40              98.2      No
5   60             100.2     Yes